import { NextRequest, NextResponse } from "next/server";
import { sendMessage } from "@/lib/band/server";
import { generateBandMessage } from "@/lib/featherless/client";

/**
 * POST /api/band/launch-workflow
 *
 * Creates a Band room + adds agents + sends a detailed professional
 * task message to the Band room, generated by Featherless AI (with
 * Grok → Venice fallback). The message @mentions all agents.
 *
 * Body: { roomId: string, prompt: string, budget?: string }
 *
 * Returns: { sent: boolean, roomId: string, messageId: string }
 */
export async function POST(req: NextRequest) {
  try {
    const { roomId, prompt, budget } = (await req.json()) as {
      roomId: string;
      prompt: string;
      budget?: string;
    };

    if (!roomId || !prompt) {
      return NextResponse.json(
        { error: "roomId and prompt are required" },
        { status: 400 },
      );
    }

    const orchKey = process.env.BAND_ORCHESTRATOR_KEY || process.env.BAND_SEND_API_KEY || "";
    if (!orchKey) {
      return NextResponse.json(
        { error: "No Band API key configured — set BAND_ORCHESTRATOR_KEY or BAND_SEND_API_KEY" },
        { status: 400 },
      );
    }

    const agentIds: Record<string, string> = {
      orchestrator: process.env.BAND_ORCHESTRATOR_ID ?? "",
      scout:        process.env.BAND_SCOUT_ID ?? "",
      risk_monitor: process.env.BAND_RISK_MONITOR_ID ?? "",
      executor:     process.env.BAND_EXECUTOR_ID ?? "",
    };

    // Generate a detailed professional task message using Featherless AI
    // Falls back to a structured template if AI generation fails
    let taskMessage: string;
    try {
      const aiMessage = await generateBandMessage("workflow-start", {
        prompt,
        budget: budget ?? "10",
        agents: ["Scout", "RiskMonitor", "Executor"],
      });
      taskMessage = aiMessage;
    } catch {
      taskMessage = buildTemplateTaskMessage(prompt, budget ?? "10");
    }

    // Send the message mentioning all agents
    const mentionIds = [
      agentIds.scout,
      agentIds.risk_monitor,
      agentIds.executor,
    ].filter((id): id is string => !!id);

    const msg = await sendMessage(roomId, taskMessage, mentionIds, { key: orchKey });
    console.log(`[band/launch-workflow] Sent detailed task to room ${roomId}: msg=${msg.id}`);

    return NextResponse.json({
      sent: true,
      roomId,
      messageId: msg.id,
      mentionIds,
      messagePreview: taskMessage.slice(0, 120),
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error("[band/launch-workflow] Error:", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

/** Fallback template when AI generation is unavailable. */
function buildTemplateTaskMessage(prompt: string, budget: string): string {
  return `**New Workflow: Automated DeFi Strategy**

**Goal**: ${prompt}
**Budget**: ${budget} USDC
**Network**: Base Mainnet

━━━━━━━━━━━━━━━━━━━━━━━━

**Agent assignments:**

🔭 **@Scout** — Begin by gathering intelligence:
  • Check live yields across supported protocols
  • Identify the best APY opportunities
  • Report findings with specific numbers

🛡️ **@RiskMonitor** — Evaluate the Scout's findings:
  • Assess protocol risk (LOW / MEDIUM / HIGH)
  • Approve or veto the proposed action
  • Provide clear reasoning

⚡ **@Executor** — Execute the approved action:
  • Perform the on-chain transaction
  • Post the transaction hash and Basescan link
  • Confirm success or report failure

━━━━━━━━━━━━━━━━━━━━━━━━

Agents: report your results in this room with full details and transaction hashes.

— CapMatrix Orchestrator`;
}
